export const CourseTemplate = {
  course_name: "",
  level: "beginner",
  language: "English",
  total_no_hours: "",
  no_of_sessions: 0,
  no_of_tests_available: 0,
  tests_available: false,
  certification: true,
  pdf_available: true,
  price: 0,
  video_url: "",
  image_url: "",
  about_course: {
    skills: [""],
    complete_description: "",
  },
  outcome: [""],
  course_content: [],
  sessions: [],
};
